DATABASE_CONNECTION_STRING = "mysql+pymysql://assistant:6548@10.0.0.52/elite"

TASKNAMES = [
    "Bounty hunting",
    "Collect Escape Pods",
    "Holoscreen Hacking",
    "Power Kills",
    "Scan Megaship Datalinks",
    "Sell for large profits",
    "Sell mined resources",
    "Sell rare goods",
    "Transport Powerplay commodities",
    "Complete aid and humanitarian missions",
    "Flood markets with low value goods",
    "Scan ships and wakes",
    "Hand in biological research samples",
    "Hand in cartography data",
    "Hand in salvage",
    "Reboot mission completion",
    "Commit crimes",
    # ODY
    "Retrieve specific goods",
    "Transfer Power classified data",
    "Transfer Power association and political data",
    "Transfer Power research and Industrial data",
    "Upload Powerplay malware",
]

TASKSHORTCODES = {
    "BTHT": "Bounty hunting",
    "CEPD": "Collect Escape Pods",
    "HSHK": "Holoscreen Hacking",
    "PKLS": "Power Kills",
    "SDLK": "Scan Megaship Datalinks",
    "SLFP": "Sell for large profits",
    "SMNR": "Sell mined resources",
    "SRGD": "Sell rare goods",
    "TPCD": "Transport Powerplay commodities",
    "CAHM": "Complete aid and humanitarian missions",
    "FMLV": "Flood markets with low value goods",
    "SSWK": "Scan ships and wakes",
    "HBRS": "Hand in biological research samples",
    "HICD": "Hand in cartography data",
    "HISV": "Hand in salvage",
    "RMCP": "Reboot mission completion",
    "CMCR": "Commit crimes",
    # ODY
    "RSGD": "Retrieve specific goods",
    "TPCL": "Transfer Power classified data",
    "TPAD": "Transfer Power association and political data",
    "TPRD": "Transfer Power research and Industrial data",
    "UPMW": "Upload Powerplay malware",
}

TASKTYPES = {
    "Combat": ["BTHT", "PKLS", "CMCR"],
    "Trading": ["SLFP", "SRGD", "FMLV", "TPCD"],
    "Mining": ["SMNR"],
    "Scanning": ["SSWK", "HICD", "SDLK"],
    "Exploration": ["HICD", "HBRS"],
    "Odyssey": ["RSGD", "TPCL", "TPAD", "TPRD", "UPMW"],
    "Aid": ["CAHM", "CEPD"],
    "Illegal": ["CMCR", "HSHK", "PKLS"],
}


POWERWEAKNESSES = {
    "ALD": ["CMCR", "SDLK"],
    "ARD": ["BTHT", "PKLS"],
    "ASD": ["HSHK", "TPCD"],
    "DPT": ["CMCR", "SDLK"],
    "EMH": ["FMLV", "HSHK"],
    "FLW": ["RSGD", "FMLV"],
    "JRA": ["CMCR", "RSGD"],
    "LYR": ["UPMW", "FMLV"],
    "NAK": ["HSHK", "FMLV"],
    "PRA": ["TPCD", "FMLV"],
    "YRG": ["CMCR", "UPMW"],
    "ZMT": ["RSGD", "SMNR"],
}

POWERS = {
    "ALD": "Arissa Lavingy-Duval",
    "ARD": "Archon Delane",
    "ASD": "Aisling Duval",
    "DPT": "Denton Patrus",
    "EMH": "Edmund Mahon",
    "FLW": "Felicia Winters",
    "JRA": "Jerome Archer",
    "LYR": "Li Yong-Rui",
    "NAK": "Nakato Kaine",
    "PRA": "Prantav Antal",
    "YRG": "Yuri Grom",
    "ZMT": "Zemina Torval",
}

HOMESYSTEMS = {
    "Kamadhenu": "ALD",
    "Achenar": "ARD",
    "Cubeo": "ASD",
    "Eotienses": "DPT",
    "Gateway": "EMH",
    "Rhea": "FLW",
    "Nanomam": "JRA",
    "Lembava": "LYR",
    "Tionisla": "NAK",
    "Polevnic": "PRA",
    "Clayakarma": "YRG",
    "Synteini": "ZMT",
}

PERMITLOCKED = [
    # independent
    "Shinrarta Dezhra",
    "Sirius",
    "van Maanen's Star",
    "Mbooni",
    "CD-43 11917",
    # federation
    "Sol",
    "Beta Hydri",
    "Vega",
    "PLX 695",
    "Ross 128",
    "Exbeur",
    "Hors",
    # empire
    "Achenar",
    "Facece",
    "Summerland",
    # alliance
    "Alioth",
]

POWERNAMES = [
    "Arissa Lavingy-Duval",
    "Archon Delane",
    "Aisling Duval",
    "Denton Patrus",
    "Edmund Mahon",
    "Felicia Winters",
    "Jerome Archer",
    "Li Yong-Rui",
    "Nakato Kaine",
    "Prantav Antal",
    "Yuri Grom",
    "Zemina Torval",
]

POWERRENFORCEACTIVITIES = {
    "ALD": ["BTHT", "CEPD", "HSHK"],
    "ARD": ["BTHT", "PKLS", "RSGD"],
    "ASD": ["BTHT", "PKLS", "RSGD"],
    "DPT": ["BTHT", "CEPD", "HSHK"],
    "EMH": ["SLFP", "SMNR", "CAHM"],
    "FLW": ["CEPD", "CAHM", "UPMW"],
    "JRA": ["BTHT", "CEPD", "HSHK"],
    "LYR": ["SLFP", "SMNR", "CAHM"],
    "NAK": ["CEPD", "CAHM", "UPMW"],
    "PRA": ["CEPD", "CAHM", "UPMW"],
    "YRG": ["BTHT", "CEPD", "HSHK"],
    "ZMT": ["SLFP", "SMNR", "CAHM"],
}

POWERCOMMODITIES = {
    # power: aquire, reinforce, undermine
    "ALD": [
        "Lavingy Corruption Reports",
        "Lavingy Garrison Supplies",
        "Lavingy Strategic Reports",
    ],
    "ARD": ["Kumo Contraband Packages", "Unmarked Military Supplies", "Marked Slaves"],
    "ASD": [
        "Aisling Media Material",
        "Aisling Sealed Contract",
        "Aisling Programme Material",
    ],
    "DPT": [
        "Marked Military Arms",
        "Patrus field supplies",
        "Patrus Garrison Supplies",
    ],
    "EMH": [
        "Alliance Trade Agreements",
        "Alliance Legislative Contract	",
        "Alliance Legislative Records",
    ],
    "FLW": ["Liberal Federal Aid", "Liberal Federal Packages", "Liberal Propaganda"],
    "JRA": [
        "Archer's Restricted Intel",
        "Archer's Field Supplies",
        "Archer's Garrison Supplies",
    ],
    "LYR": [
        "Sirius Franchise Package",
        "Sirius Industrial Equipment",
        "Sirius Corporate Contract",
    ],
    "NAK": ["Kaine Lobbying Material", "Kaine Aid Supplies", "Kaine Misinformation"],
    "PRA": ["Utopian Publicity", "Utopian Supplies", "Utopian Dissident"],
    "YRG": [
        "Grom Underground Support",
        "Grom Military Supplies",
        "Grom Counter Intelligence",
    ],
    "ZMT": ["Torval Trade Agreements", "Torval Deeds", "Torval Political Servants"],
}

RAREGOODS = {
    "Aepyornis Egg": "Glushko Station/47 Ceti",
    "Aganippe Rush": "Julian Market/Aganippe",
    "Alacarakmo Skin Art": "Weyl Gateway/Alacarakmo",
    "Albino Quechua Mammoth Meat": "Crown Ring/Quechua",
    "Altairian Skin": "Solo Orbiter/Altair",
    "Alya Body Soap": "Malaspina Gateway/Alya",
    "Anduliga Fire Works": "Celsius Estate/Anduliga",
    "Any Na Coffee": "Libby Orbital/Any Na",
    "Apa Vietii": "Forester's Choice/Upaniklis",
    "Arouca Conventual Sweets": "Shipton Orbital/Arouca",
    "AZ Cancri Formula 42": "Fisher Station/AZ Cancri",
    "Azure Milk": "George Lucas/Leesti",
    "Baked Greebles": "Bamford Ring/38 Virginis",
    "Baltah'sine Vacuum Krill": "Baltha'sine Station/Baltah'Sine",
    "Banki Amphbious Leather": "Antonio de Andrade Vista/Banki",
    "Bast Snake Gin": "Hart Station/Bast",
    "Belalans Ray Leather": "Boscovich Ring/Belalans",
    "Borasetani Pathogenetics": "Katzenstein Terminal/Borasetani",
    "Bucky Ball Beer Mats": "Rebuy Prospect/Fullerene C60",
    "Burnham Bile Distillate": "Burnham Beacon/HIP 59533",
    "CD-75 Kitten Brand Coffee": "Kirk Dock/CD-75 661",
    "Centauri Mega Gin": "Hutton Orbital/Alpha Centauri",
    "Ceremonial Heike Tea": "Brunel City/Heike",
    "Ceti Rabbits": "Kaufmanis Hub/47 Ceti",
    "Chameleon Cloth": "Smith Reserve/LDS 883",
    "Chateau De Aegaeon": "Schweikart Station/Aegaeon",
    "Cherbones Blood Crystals": "Chalker Landing/Cherbones",
    "Chi Eridani Marine Paste": "Steve Masters Station/Chi Eridani",
    "Coquim Spongiform Victuals": "Hirayama Installation/Coquim",
    "Crom Silver Fesh": "Chorel Survey/Crom",
    "Crystalline Spheres": "Snow Moon/Bento",
    "Damna Carapaces": "Nemere Market/Damna",
    "Delta Phoenicis Palms": "Trading Post/Delta Phoenicis",
    "Deuringas Truffles": "Shukor Hub/Deuringas",
    "Diso Ma Corn": "Shifnalport/Diso",
    "Duradrives": "Cowper Dock/Anima",
    "Eden Apples Of Aerial": "Andrade Legacy/Aerial",
    "Eleu Thermals": "Finney Dock/Eleu",
    "Eranin Pearl Whisky": "Azeban City/Eranin",
    "Eshu Umbrellas": "Shajn Terminal/Eshu",
    "Esuseku Caviar": "Savinykh Orbital/Esuseku",
    "Ethgreze Tea Buds": "Bloch Station/Ethgreze",
    "Fujin Tea": "Futen Spaceport/Fujin",
    "Geawen Dance Dust": "Obruchev Legacy/Geawen",
    "Gerasian Gueuze Beer": "Yurchikhin Port/Geras",
    "Giant Irukama Snails": "Blaauw City/Irukama",
    "Giant Verrix": "Greeboski's Outpost/Phiagre",
    "Gilya Signature Weapons": "Bell Orbital/Gilya",
    "Goman Yaupon Coffee": "Gustav Sporer Port/Goman",
    "Haiden Black Brew": "Searfoss Enterprise/Haiden",
    "Harma Silver Sea Rum": "Gabriel Enterprise/Harma",
    "Havasupai Dream Catcher": "Lovelace Port/Havasupai",
    "Helvetitj Pearls": "Friend Orbital/Helvetitj",
    "HIP 10175 Bush Meat": "Stefanyshyn-Piper Station/HIP 10175",
    "HIP 118311 Swarm": "Lubbock Market/HIP 118311",
    "HIP Organophosphates": "Stasheff Colony/HIP 80364",
    "HIP Proto-Squid": "Andersson Station/HIP 41181",
    "Holva Duelling Blades": "Kreutz Orbital/Holva",
    "Honesty Pills": "King Gateway/LP 375-25",
    "HR 7221 Wheat": "Veron City/HR 7221",
    "Indi Bourbon": "Mansfield Orbiter/Epsilon Indi",
    "Jaques Quinentian Still": "Jaques Station/Colonia",
    "Jaradharre Puzzle Box": "Gohar Station/Jaradharre",
    "Jaroua Rice": "McCool City/Jaroua",
    "Jotun Mookah": "Icelock/Jotun",
    "Kachirigin Filter Leeches": "Nowak Orbital/Kachirigin",
    "Kamitra Cigars": "Hammel Terminal/Kamitra",
    "Kamorin Historic Weapons": "Godwin Vision/Kamorin",
    "Karetii Couture": "Sinclair Platform/Karetii",
    "Karsuki Locusts": "West Market/Karsuki Ti",
    "Kinago Violins": "Fozard Ring/Kinago",
    "Kongga Ale": "Laplace Ring/Kongga",
    "Korro Kung Pellets": "Lonchakov Orbital/Korro Kung",
    "Lavian Brandy": "Lave Station/Lave",
    "Leathery Eggs": "Ridley Scott/Zaonce",
    "Leestian Evil Juice": "George Lucas/Leesti",
    "Live Hecate Sea Worms": "RJH1972/Hecate",
    "LTT Hyper Sweet": "Smeaton Orbital/LTT 9360",
    "Lucan Onionhead": "Cassie-L-Peia/Tanmark",
    "Lyrae Weed": "Budrys Ring/16 Lyrae",
    "Master Chefs": "Pataarchy Corporate/Viracocha",
    "Mechucos High Tea": "Brandenstein Port/Mechucos",
    "Medb Starlube": "Vela Dock/Medb",
    "Mokojing Beast Feast": "Noli Terminal/Mokojing",
    "Momus Bog Spaniel": "Tartarus Point/Momus Reach",
    "Motrona Experience Jelly": "Pinzon Dock/Dea Motrona",
    "Mukusubii Chitin-Os": "Ledyard Dock/Mukusubii",
    "Mulachi Giant Fungus": "Clark Terminal/Mulachi",
    "Nanomedicines": "Elion Dock/Kuma",
    "Neritus Berries": "Toll Ring/Neritus",
    "Ngadandari Fire Opals": "Napier Terminal/Ngadandari",
    "Nguna Modern Antiques": "Biggle Hub/Nguna",
    "Njangari Saddles": "Lee Hub/Njangari",
    "Non Euclidian Exotanks": "Euclid Terminal/LTT 8517",
    "Ochoeng Chillies": "Roddenberry Gateway/Ochoeng",
    "Onionhead": "Harvestport/Kappa Fornacis",
    "Onionhead Alpha Strain": "Navigator Market/Xelabara",
    "Onionhead Beta Strain": "La Cosa City/HIP 112974",
    "Ophiuch Exino Artefacts": "Katzenstein Dock/36 Ophiuchi",
    "Orrerian Vicious Brew": "Sharon Lee Free Market/Orrere",
    "Pantaa Prayer Sticks": "Zamka Platform/George Pantazis",
    "Pavonis Ear Grubs": "Hooper Relay/Delta Pavonis",
    "Personal Gifts": "Frost Dock/Njambalba",
    "Platinum Alloy": "Artzybasheff Terminal/Nahuatl",
    "Rajukru Multi-Stoves": "Snyder Terminal/Rajukru",
    "Rapa Bao Snake Skins": "Flagg Gateway/Rapa Bao",
    "Rusani Old Smokey": "Fernandes Market/Rusani",
    "Sanuma Decorative Meat": "Dunyach Gateway/Sanuma",
    "Saxon Wine": "Hunt Enterprise/9 Aurigae",
    "Shan's Charis Orchid": "Baird Gateway/Arque",
    "Soontill Relics": "Cheranovsky City/Ngurii",
    "Sothis Crystalline Gold": "Newholm Station/Sothis",
    "Tanmark Tranquil Tea": "Cassie-L-Peia/Tanmark",
    "Tarach Spice": "Tranquillity/Tarach Tor",
    "Tauri Chimes": "Porta/39 Tauri",
    "Terra Mater Blood Bores": "Gr8minds/Terra Mater",
    "The Hutton Mug": "Hutton Orbital/Alpha Centauri"
}

RAREGOODS.update({
    "The Waters of Shintara": "Jameson Memorial/Shinrarta Dezhra",
    "Thrutis Cream": "Kingsbury Dock/Thrutis",
    "Tiegfries Synthsilk": "Larbalestier Dock/Tiegfries",
    "Tiolce Waste2Paste Units": "Gordon Terminal/Tiolce",
    "Toxandji Virocide": "Tsunenaga Orbital/Toxandji",
    "Ultra-Compact Processor Prototypes": "Langford Enterprise/17 Lyrae",
    "Uszaian Tree Grub": "Guest Installation/Uszaa",
    "Utgaroar Millennial Eggs": "Fort Klarix/Utgaroar",
    "Uzumoku Low-G Wings": "Sverdrup Ring/Uzumoku",
    "V Herculis Body Rub": "Kaku Plant/V1090 Herculis",
    "Vanayequi Ceratomorpha Fur": "Clauss Hub/Vanayequi",
    "Vega Slimweed": "Taylor City/Vega",
    "Vidavantian Lace": "Lee Mines/Vidavanta",
    "Void Extract Coffee": "Ehrlich Orbital/LFT 1421",
    "Volkhab Bee Drones": "Vernadsky Dock/Volkhab",
    "Wheemete Wheat Cakes": "Eisinga Enterprise/Wheemete",
    "Witchhaul Kobe Beef": "Hornby Terminal/Witchhaul",
    "Wolf Fesh": "Saunders's Dive/Wolf 1301",
    "Wulpa Hyperbore Systems": "Williams Gateway/Wulpa",
    "Wuthielo Ku Froth": "Tarter Dock/Wuthielo Ku",
    "Xihe Biomorphic Companions": "Zhen Dock/Xihe",
    "Yaso Kondi Leaf": "Wheeler Market/Yaso Kondi",
    "Zeessze Ant Grub Glue": "Nicollier Hanger/Zeessze"
})


if __name__ == "__main__":
    for key, item in RAREGOODS.items():
        item_parts = item.split("/")
        system_name = item_parts[1]
        station_name = item_parts[0]
        print(f"INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ('{key}', '{system_name}', '{station_name}');")