DROP TABLE IF EXISTS Raregoods;
CREATE TABLE Raregoods (good_name VARCHAR(255) PRIMARY KEY, system_name VARCHAR(255), station_name VARCHAR(255));
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Aepyornis Egg", "47 Ceti", "Glushko Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Aganippe Rush", "Aganippe", "Julian Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Alacarakmo Skin Art", "Alacarakmo", "Weyl Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Albino Quechua Mammoth Meat", "Quechua", "Crown Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Altairian Skin", "Altair", "Solo Orbiter");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Alya Body Soap", "Alya", "Malaspina Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Anduliga Fire Works", "Anduliga", "Celsius Estate");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Any Na Coffee", "Any Na", "Libby Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Apa Vietii", "Upaniklis", "Forester's Choice");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Arouca Conventual Sweets", "Arouca", "Shipton Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("AZ Cancri Formula 42", "AZ Cancri", "Fisher Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Azure Milk", "Leesti", "George Lucas");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Baked Greebles", "38 Virginis", "Bamford Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Baltah'sine Vacuum Krill", "Baltah'Sine", "Baltha'sine Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Banki Amphbious Leather", "Banki", "Antonio de Andrade Vista");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Bast Snake Gin", "Bast", "Hart Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Belalans Ray Leather", "Belalans", "Boscovich Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Borasetani Pathogenetics", "Borasetani", "Katzenstein Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Bucky Ball Beer Mats", "Fullerene C60", "Rebuy Prospect");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Burnham Bile Distillate", "HIP 59533", "Burnham Beacon");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("CD-75 Kitten Brand Coffee", "CD-75 661", "Kirk Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Centauri Mega Gin", "Alpha Centauri", "Hutton Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Ceremonial Heike Tea", "Heike", "Brunel City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Ceti Rabbits", "47 Ceti", "Kaufmanis Hub");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Chameleon Cloth", "LDS 883", "Smith Reserve");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Chateau De Aegaeon", "Aegaeon", "Schweikart Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Cherbones Blood Crystals", "Cherbones", "Chalker Landing");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Chi Eridani Marine Paste", "Chi Eridani", "Steve Masters Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Coquim Spongiform Victuals", "Coquim", "Hirayama Installation");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Crom Silver Fesh", "Crom", "Chorel Survey");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Crystalline Spheres", "Bento", "Snow Moon");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Damna Carapaces", "Damna", "Nemere Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Delta Phoenicis Palms", "Delta Phoenicis", "Trading Post");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Deuringas Truffles", "Deuringas", "Shukor Hub");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Diso Ma Corn", "Diso", "Shifnalport");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Duradrives", "Anima", "Cowper Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Eden Apples Of Aerial", "Aerial", "Andrade Legacy");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Eleu Thermals", "Eleu", "Finney Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Eranin Pearl Whisky", "Eranin", "Azeban City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Eshu Umbrellas", "Eshu", "Shajn Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Esuseku Caviar", "Esuseku", "Savinykh Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Ethgreze Tea Buds", "Ethgreze", "Bloch Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Fujin Tea", "Fujin", "Futen Spaceport");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Geawen Dance Dust", "Geawen", "Obruchev Legacy");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Gerasian Gueuze Beer", "Geras", "Yurchikhin Port");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Giant Irukama Snails", "Irukama", "Blaauw City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Giant Verrix", "Phiagre", "Greeboski's Outpost");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Gilya Signature Weapons", "Gilya", "Bell Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Goman Yaupon Coffee", "Goman", "Gustav Sporer Port");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Haiden Black Brew", "Haiden", "Searfoss Enterprise");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Harma Silver Sea Rum", "Harma", "Gabriel Enterprise");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Havasupai Dream Catcher", "Havasupai", "Lovelace Port");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Helvetitj Pearls", "Helvetitj", "Friend Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("HIP 10175 Bush Meat", "HIP 10175", "Stefanyshyn-Piper Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("HIP 118311 Swarm", "HIP 118311", "Lubbock Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("HIP Organophosphates", "HIP 80364", "Stasheff Colony");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("HIP Proto-Squid", "HIP 41181", "Andersson Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Holva Duelling Blades", "Holva", "Kreutz Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Honesty Pills", "LP 375-25", "King Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("HR 7221 Wheat", "HR 7221", "Veron City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Indi Bourbon", "Epsilon Indi", "Mansfield Orbiter");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Jaques Quinentian Still", "Colonia", "Jaques Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Jaradharre Puzzle Box", "Jaradharre", "Gohar Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Jaroua Rice", "Jaroua", "McCool City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Jotun Mookah", "Jotun", "Icelock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Kachirigin Filter Leeches", "Kachirigin", "Nowak Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Kamitra Cigars", "Kamitra", "Hammel Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Kamorin Historic Weapons", "Kamorin", "Godwin Vision");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Karetii Couture", "Karetii", "Sinclair Platform");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Karsuki Locusts", "Karsuki Ti", "West Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Kinago Violins", "Kinago", "Fozard Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Kongga Ale", "Kongga", "Laplace Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Korro Kung Pellets", "Korro Kung", "Lonchakov Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Lavian Brandy", "Lave", "Lave Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Leathery Eggs", "Zaonce", "Ridley Scott");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Leestian Evil Juice", "Leesti", "George Lucas");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Live Hecate Sea Worms", "Hecate", "RJH1972");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("LTT Hyper Sweet", "LTT 9360", "Smeaton Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Lucan Onionhead", "Tanmark", "Cassie-L-Peia");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Lyrae Weed", "16 Lyrae", "Budrys Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Master Chefs", "Viracocha", "Pataarchy Corporate");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Mechucos High Tea", "Mechucos", "Brandenstein Port");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Medb Starlube", "Medb", "Vela Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Mokojing Beast Feast", "Mokojing", "Noli Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Momus Bog Spaniel", "Momus Reach", "Tartarus Point");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Motrona Experience Jelly", "Dea Motrona", "Pinzon Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Mukusubii Chitin-Os", "Mukusubii", "Ledyard Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Mulachi Giant Fungus", "Mulachi", "Clark Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Nanomedicines", "Kuma", "Elion Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Neritus Berries", "Neritus", "Toll Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Ngadandari Fire Opals", "Ngadandari", "Napier Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Nguna Modern Antiques", "Nguna", "Biggle Hub");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Njangari Saddles", "Njangari", "Lee Hub");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Non Euclidian Exotanks", "LTT 8517", "Euclid Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Ochoeng Chillies", "Ochoeng", "Roddenberry Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Onionhead", "Kappa Fornacis", "Harvestport");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Onionhead Alpha Strain", "Xelabara", "Navigator Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Onionhead Beta Strain", "HIP 112974", "La Cosa City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Ophiuch Exino Artefacts", "36 Ophiuchi", "Katzenstein Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Orrerian Vicious Brew", "Orrere", "Sharon Lee Free Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Pantaa Prayer Sticks", "George Pantazis", "Zamka Platform");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Pavonis Ear Grubs", "Delta Pavonis", "Hooper Relay");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Personal Gifts", "Njambalba", "Frost Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Platinum Alloy", "Nahuatl", "Artzybasheff Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Rajukru Multi-Stoves", "Rajukru", "Snyder Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Rapa Bao Snake Skins", "Rapa Bao", "Flagg Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Rusani Old Smokey", "Rusani", "Fernandes Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Sanuma Decorative Meat", "Sanuma", "Dunyach Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Saxon Wine", "9 Aurigae", "Hunt Enterprise");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Shan's Charis Orchid", "Arque", "Baird Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Soontill Relics", "Ngurii", "Cheranovsky City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Sothis Crystalline Gold", "Sothis", "Newholm Station");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Tanmark Tranquil Tea", "Tanmark", "Cassie-L-Peia");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Tarach Spice", "Tarach Tor", "Tranquillity");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Tauri Chimes", "39 Tauri", "Porta");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Terra Mater Blood Bores", "Terra Mater", "Gr8minds");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("The Hutton Mug", "Alpha Centauri", "Hutton Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("The Waters of Shintara", "Shinrarta Dezhra", "Jameson Memorial");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Thrutis Cream", "Thrutis", "Kingsbury Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Tiegfries Synthsilk", "Tiegfries", "Larbalestier Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Tiolce Waste2Paste Units", "Tiolce", "Gordon Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Toxandji Virocide", "Toxandji", "Tsunenaga Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Ultra-Compact Processor Prototypes", "17 Lyrae", "Langford Enterprise");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Uszaian Tree Grub", "Uszaa", "Guest Installation");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Utgaroar Millennial Eggs", "Utgaroar", "Fort Klarix");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Uzumoku Low-G Wings", "Uzumoku", "Sverdrup Ring");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("V Herculis Body Rub", "V1090 Herculis", "Kaku Plant");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Vanayequi Ceratomorpha Fur", "Vanayequi", "Clauss Hub");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Vega Slimweed", "Vega", "Taylor City");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Vidavantian Lace", "Vidavanta", "Lee Mines");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Void Extract Coffee", "LFT 1421", "Ehrlich Orbital");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Volkhab Bee Drones", "Volkhab", "Vernadsky Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Wheemete Wheat Cakes", "Wheemete", "Eisinga Enterprise");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Witchhaul Kobe Beef", "Witchhaul", "Hornby Terminal");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Wolf Fesh", "Wolf 1301", "Saunders's Dive");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Wulpa Hyperbore Systems", "Wulpa", "Williams Gateway");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Wuthielo Ku Froth", "Wuthielo Ku", "Tarter Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Xihe Biomorphic Companions", "Xihe", "Zhen Dock");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Yaso Kondi Leaf", "Yaso Kondi", "Wheeler Market");
INSERT INTO Raregoods (good_name, system_name, station_name) VALUES ("Zeessze Ant Grub Glue", "Zeessze", "Nicollier Hanger");
